/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zalezone_imagemagic_opencv_grayprocess_ImageProc */

#ifndef _Included_zalezone_imagemagic_opencv_grayprocess_ImageProc
#define _Included_zalezone_imagemagic_opencv_grayprocess_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zalezone_imagemagic_opencv_grayprocess_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_zalezone_imagemagic_opencv_grayprocess_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
