/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zalezone_imagemagic_opencv_officialsample_NativeImageUtil */

#ifndef _Included_zalezone_imagemagic_opencv_officialsample_NativeImageUtil
#define _Included_zalezone_imagemagic_opencv_officialsample_NativeImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zalezone_imagemagic_opencv_officialsample_NativeImageUtil
 * Method:    FindFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_zalezone_imagemagic_opencv_officialsample_NativeImageUtil_FindFeatures
  (JNIEnv *, jclass, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif
